//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatLanguage.Properties
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OOProjectEntities : DbContext
    {
        public OOProjectEntities()
            : base("name=OOProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Framework> Framework { get; set; }
        public virtual DbSet<Ide> Ide { get; set; }
        public virtual DbSet<Lang> Lang { get; set; }
        public virtual DbSet<Tech> Tech { get; set; }
    }
}
