//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Projekt_Semestralny.Properties
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Framework
    {
        public int id { get; set; }
        public int id_lang { get; set; }
        public string Framework1 { get; set; }
    
        public virtual Lang Lang { get; set; }
    }
}
